apiVersion: v1
kind: Service
metadata:
  name: devops-project-2022-frontend-service
spec:
  selector:
    app: my-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-2022-frontend-deployment
  labels:
    app: my-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: frontend
  template:
    metadata:
      labels:
        app: my-app
        tier: frontend
    spec:
      containers:
      - name: devops-project-2022-frontend-container
        image: petrovskiemil/devops-project-2022-frontend-hardcoded-clusterip
        ports:
        - containerPort: 3000
      restartPolicy: Always