apiVersion: v1
kind: Service
metadata:
  name: devops-project-2022-mongodb-service
spec:
  selector:
    app: my-app
    tier: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-2022-mongodb-deployment
  labels:
    app: my-app
    tier: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: mongodb
  template:
    metadata:
      labels:
        app: my-app
        tier: mongodb
    spec:
      containers:
      - name: devops-project-2022-mongodb-container
        image: petrovskiemil/devops-project-2022-mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
      restartPolicy: Always