apiVersion: v1
kind: Service
metadata:
  name: devops-project-2022-backend-service
spec:
  clusterIP: 10.98.232.78
  selector:
    app: my-app
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backenddeployment.service.port }}
      targetPort: 8080