apiVersion: v1
kind: Service
metadata:
  name: devops-project-2022-frontend-service
spec:
  selector:
    app: my-app
    tier: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontenddeployment.service.port }}
      targetPort: 3000